brand:
  name: Direct Advisory
menu-string: Menu

nav:
  - title: Serviços
    url: '#services'
  - title: Portfolio
    url: '#portfolio'
  - title: Sobre
    url: '#about'
  - title: Contato
    url: '#team'
  - title: 
    url: '#'

copyright: Copyright &copy; Direct Advisory v.1 2019

social-buttons:
  - icon: fa fa-instagram
    url: 'https://www.instagram.com/directadvisory/' 


quicklinks:
  - title: Privacy Policy
    url: '#'
  - title: Terms of Use
    url: '#'

modal:
  date-string: 'Date: '
  client-string: 'Client: '
  category-string: 'Category: '
  close-icon: 'fa fa-times'
  close-string: 'Close Project'
